version: '3.9'

services:
  frontend:
    command: gulp watch
    container_name: fabianmaria_frontend
    networks:
      - fabianmaria-network
    build:
      context: "./"
      dockerfile: "./docker/frontend/Dockerfile"
    env_file:
      - .env
    volumes:
      - "./drupal-dev/frontend:/app"
      - "/app/node_modules"
      - "./drupal-dev/web/themes/custom/:/app/themes/custom/"
  mysql:
    container_name: fabianmaria_mysql
    networks:
      - fabianmaria-network
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - 3306:3306
  nginx:
    container_name: fabianmaria_nginx
    networks:
      - fabianmaria-network
    build:
      context: "./"
      dockerfile: "./docker/nginx/Dockerfile"
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./drupal-dev/web/modules/custom/:/var/www/html/web/modules/custom/"
      - "./drupal-dev/web/themes/custom/:/var/www/html/web/themes/custom/"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "shared-file-system:/var/www/html/"
    env_file:
      - .env
  php:
    container_name: fabianmaria_php
    networks:
      - fabianmaria-network
    build:
      context: "./"
      dockerfile: "./docker/php/Dockerfile"
    volumes:
      - "./drupal-dev/web/modules/custom/:/var/www/html/web/modules/custom/"
      - "./drupal-dev/web/themes/custom/:/var/www/html/web/themes/custom/"
      - "./drupal-dev/config/:/var/www/html/config/"
      - "./drupal-dev/composer.json:/var/www/html/composer.json"
      - "./drupal-dev/composer.lock:/var/www/html/composer.lock"
      - "./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini"
      - "./docker/php/conf.d/:/usr/local/etc/php/conf.d/"
      - "./docker/php/php.ini-development:/usr/local/etc/php/php.ini"
      - "./drupal-config/settings.local.php:/var/www/html/web/sites/default/settings.local.php"
      - "./drupal-config/local.development.services.yml:/var/www/html/web/sites/local.development.services.yml"
      - "shared-file-system:/var/www/html/"
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - 9000
      - 9003
  # mailhog:
  #   container_name: fabianmaria_mailhog
  #   networks:
  #     - fabianmaria-network
  #   image: mailhog/mailhog:latest
  #   restart: always
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

networks:
  fabianmaria-network:
    driver: bridge
volumes:
  shared-file-system:
  shared-custom-themes: